### ISSUE TITLE
Pool temperature sensor

### ISSUE THREAD

**Issue by jfournierphoto** [jfournierphoto/Home-Assistant-Config#23]
# Pool Temp

Figure a way to use the DS18B20 sensr to monitor the pool water temperature.

## To Do
- [x] Obtain DS18B20 sensor
- [x] Obtain 4mm pneumatic connector
- [x] Obtain M6 forming screw
- [x] Run Cable to the new Garage 2.0 hub (check if any distance restriction)
- [x] Program in Esphome or Tasmota

## Plan

The idea is to drill a hole in the return pipe just outside the garage and install the DS18B20 through the 4mm pneumatic connector. This will be the temp just out of the pool.

## Hardware

Will be using a wemos D1 mini:

D1 : DHT11 temp and humidity sensor
D5 : DS18b20 temp sensor

```
esphome:
  name: piscine
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: WIFI
  password: WIFI PASSWORD

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

dallas:
  - pin: D5

sensor:
  - platform: dht
    pin: D1
    model: dht11
    temperature:
      name: "garage temp"
      accuracy_decimals: 2
    humidity:
      name: "garage hum"
    update_interval: 60s

  - platform: dallas
    address: 0xDC000005B5C71A28
    name: "ds18b20 piscine"
    filters:
      - lambda: return x * (9.0/5.0) + 30;
    unit_of_measurement: "°F"
    accuracy_decimals: 1

binary_sensor:
  - platform: status
    name: "Piscine_Status"
```
